# Generated by Django 5.1.2 on 2024-11-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
