# Generated by Django 5.1.2 on 2024-10-25 15:54

import blog.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to=blog.utils.PathAndRename('profile'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg']), blog.utils.validate_image_size]),
        ),
    ]
