# Generated by Django 5.1.2 on 2024-11-02 14:38

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, default='No details available for this user', validators=[blog.utils.validate_word_count]),
        ),
    ]
